export enum HttpErrorCode {
    ERR_CANNOT_APPROVE = 'ERR_CANNOT_APPROVE',
    ERR_CANNOT_CANCEL = 'ERR_CANNOT_CANCEL',
    ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
    ERR_UNAUTHORIZED_INVALID_USER = 'ERR_UNAUTHORIZED_INVALID_USER',
    ERR_UNAUTHORIZED_INVALID_PASSWORD = 'ERR_UNAUTHORIZED_INVALID_PASSWORD',
    ERR_UNAUTHORIZED_NOT_ENOUGH_PERMISSIONS = 'ERR_UNAUTHORIZED_NOT_ENOUGH_PERMISSIONS',
    ERR_AUTH_TOKEN_EXPIRED = 'ERR_AUTH_TOKEN_EXPIRED',
    ERR_VALIDATION = 'ERR_VALIDATION',
    ERR_INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR',
}
